CREATE DATABASE aura;

USE aura;

CREATE TABLE challenge (
    CHALLENGE_ID INT PRIMARY KEY,
    CHALLENGE_NAME VARCHAR(100),
    CHALLENGE_DATE DATE,
    CHALLENGE_DESC VARCHAR(1000),
    CHALLENGE_USER INT
);

CREATE TABLE account (
    ACCOUNT_ID INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE achieved (
    ACCOUNT_ID INT,
    CHALLENGE_ID INT,
    PRIMARY KEY(ACCOUNT_ID, CHALLENGE_ID),
    FOREIGN KEY(ACCOUNT_ID) REFERENCES account(ACCOUNT_ID),
    FOREIGN KEY(CHALLENGE_ID) REFERENCES challenge(CHALLENGE_ID)
);